export enum ColoursEnum {
  black = '#333333',
  white = '#FFFFFF',
  transparentWhite = 'rgb(255, 255, 255, 0.9)',
  lightGrey = '#F8F8F8',
  grey = '#D1D1D1',
  darkGrey = '#707070',
  orange = '#FFBF00',
  purple = '#8000FF',
  red = '#F44336',
  mustard = '#FFBF00',
}

export enum GraphColoursEnum {
  red = '#F44336',
  pink = '#E91E63',
  violet = '#9C27B0',
  purple = '#673AB7',
  navy = '#3F51B5',
  blue = '#2196F3',
  turquoise = '#00BCD4',
  greenBlue = '#009688',
  green = '#4CAF50',
  lightGreen = '#8BC34A',
  lime = '#CDDC39',
  yellow = '#FFEB3B',
  sunrise = '#FFC107',
  orange = '#FF9800',
  sunset = '#FF5722',
  brown = '#795548',
  grey = '#9E9E9E',
  metal = '#607D8B',
}

export const GraphColourList = [
  GraphColoursEnum.red,
  GraphColoursEnum.pink,
  GraphColoursEnum.violet,
  GraphColoursEnum.purple,
  GraphColoursEnum.navy,
  GraphColoursEnum.blue,
  GraphColoursEnum.turquoise,
  GraphColoursEnum.greenBlue,
  GraphColoursEnum.green,
  GraphColoursEnum.lightGreen,
  GraphColoursEnum.lime,
  GraphColoursEnum.yellow,
  GraphColoursEnum.sunrise,
  GraphColoursEnum.orange,
  GraphColoursEnum.sunset,
  GraphColoursEnum.brown,
  GraphColoursEnum.grey,
  GraphColoursEnum.metal,
];
