/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2019-09-08 22:29:45 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:5432/twine-api-clone -t access_role -t access_role_permission -t api_token -t cls_survey_benchmark_data -t community_business -t community_business_region -t community_business_sector -t confirm_add_role -t data_sync_log -t disability -t ethnicity -t frontline_account -t frontline_survey_answer -t frontline_survey_question -t funding_body -t funding_programme -t funding_programme_community_business -t gender -t geography_columns -t geometry_columns -t knex_migrations -t knex_migrations_lock -t login_event -t nps_survey_benchmark_data -t organisation -t outreach_campaign -t outreach_campaign_target -t outreach_campaign_target_type -t outreach_meeting -t outreach_meeting_type -t outreach_type -t permission -t raster_columns -t raster_overviews -t single_use_token -t spatial_ref_sys -t subscription -t subscription_type -t training_session -t training_session_organisation -t user_account -t user_account_access_role -t user_account_active_day -t user_secret_reset -t visit_activity -t visit_activity_category -t visit_feedback -t visit_log -t volunteer_activity -t volunteer_admin_code -t volunteer_hours_log -t volunteer_project -s public
 *
 */

export type enum_access_type = 'delete' | 'read' | 'write';
export type enum_invitation_status = 'accepted' | 're-sent' | 'revoked' | 'sent';
export type enum_permission_level = 'all' | 'child' | 'own' | 'parent' | 'sibling';
export type enum_subscription_status = 'active' | 'closed' | 'frozen' | 'trial';
export type enum_turnover_band = '<£100k' | '>£10m' | '£100k-£250k' | '£1m-£5m' | '£250k-£500k' | '£500k-£750k' | '£5m-£10m' | '£750k-£1m';

export namespace access_roleFields {
    export type access_role_id = number;
    export type access_role_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface access_role {
    access_role_id: access_roleFields.access_role_id;
    access_role_name: access_roleFields.access_role_name;
    created_at: access_roleFields.created_at;
    modified_at: access_roleFields.modified_at;
    deleted_at: access_roleFields.deleted_at;

}

export namespace access_role_permissionFields {
    export type access_role_id = number;
    export type permission_id = number;

}

export interface access_role_permission {
    access_role_id: access_role_permissionFields.access_role_id;
    permission_id: access_role_permissionFields.permission_id;

}

export namespace api_tokenFields {
    export type api_token_id = number;
    export type api_token_name = string;
    export type api_token_access = string;
    export type api_token = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface api_token {
    api_token_id: api_tokenFields.api_token_id;
    api_token_name: api_tokenFields.api_token_name;
    api_token_access: api_tokenFields.api_token_access;
    api_token: api_tokenFields.api_token;
    created_at: api_tokenFields.created_at;
    modified_at: api_tokenFields.modified_at;
    deleted_at: api_tokenFields.deleted_at;

}

export namespace cls_survey_benchmark_dataFields {
    export type cls_survey_benchmark_data_id = number;
    export type frontline_survey_question_id = number;
    export type community_business_region_id = number;
    export type score = number;
    export type benchmark_year = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface cls_survey_benchmark_data {
    cls_survey_benchmark_data_id: cls_survey_benchmark_dataFields.cls_survey_benchmark_data_id;
    frontline_survey_question_id: cls_survey_benchmark_dataFields.frontline_survey_question_id;
    community_business_region_id: cls_survey_benchmark_dataFields.community_business_region_id;
    score: cls_survey_benchmark_dataFields.score;
    benchmark_year: cls_survey_benchmark_dataFields.benchmark_year;
    created_at: cls_survey_benchmark_dataFields.created_at;
    modified_at: cls_survey_benchmark_dataFields.modified_at;
    deleted_at: cls_survey_benchmark_dataFields.deleted_at;

}

export namespace community_businessFields {
    export type organisation_id = number;
    export type community_business_region_id = number;
    export type community_business_sector_id = number;
    export type address_1 = string | null;
    export type address_2 = string | null;
    export type town_city = string | null;
    export type post_code = string | null;
    export type coordinates = any | null;
    export type logo_url = string | null;
    export type turnover_band = enum_turnover_band | null;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface community_business {
    organisation_id: community_businessFields.organisation_id;
    community_business_region_id: community_businessFields.community_business_region_id;
    community_business_sector_id: community_businessFields.community_business_sector_id;
    address_1: community_businessFields.address_1;
    address_2: community_businessFields.address_2;
    town_city: community_businessFields.town_city;
    post_code: community_businessFields.post_code;
    coordinates: community_businessFields.coordinates;
    logo_url: community_businessFields.logo_url;
    turnover_band: community_businessFields.turnover_band;
    created_at: community_businessFields.created_at;
    modified_at: community_businessFields.modified_at;
    deleted_at: community_businessFields.deleted_at;

}

export namespace community_business_regionFields {
    export type community_business_region_id = number;
    export type region_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface community_business_region {
    community_business_region_id: community_business_regionFields.community_business_region_id;
    region_name: community_business_regionFields.region_name;
    created_at: community_business_regionFields.created_at;
    modified_at: community_business_regionFields.modified_at;
    deleted_at: community_business_regionFields.deleted_at;

}

export namespace community_business_sectorFields {
    export type community_business_sector_id = number;
    export type sector_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface community_business_sector {
    community_business_sector_id: community_business_sectorFields.community_business_sector_id;
    sector_name: community_business_sectorFields.sector_name;
    created_at: community_business_sectorFields.created_at;
    modified_at: community_business_sectorFields.modified_at;
    deleted_at: community_business_sectorFields.deleted_at;

}

export namespace confirm_add_roleFields {
    export type confirm_add_role_id = number;
    export type user_account_id = number;
    export type single_use_token_id = number;

}

export interface confirm_add_role {
    confirm_add_role_id: confirm_add_roleFields.confirm_add_role_id;
    user_account_id: confirm_add_roleFields.user_account_id;
    single_use_token_id: confirm_add_roleFields.single_use_token_id;

}

export namespace data_sync_logFields {
    export type data_sync_log_id = number;
    export type foreign_key = number;
    export type table_name = string;
    export type synced_at = Date;

}

export interface data_sync_log {
    data_sync_log_id: data_sync_logFields.data_sync_log_id;
    foreign_key: data_sync_logFields.foreign_key;
    table_name: data_sync_logFields.table_name;
    synced_at: data_sync_logFields.synced_at;

}

export namespace disabilityFields {
    export type disability_id = number;
    export type disability_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface disability {
    disability_id: disabilityFields.disability_id;
    disability_name: disabilityFields.disability_name;
    created_at: disabilityFields.created_at;
    modified_at: disabilityFields.modified_at;
    deleted_at: disabilityFields.deleted_at;

}

export namespace ethnicityFields {
    export type ethnicity_id = number;
    export type ethnicity_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface ethnicity {
    ethnicity_id: ethnicityFields.ethnicity_id;
    ethnicity_name: ethnicityFields.ethnicity_name;
    created_at: ethnicityFields.created_at;
    modified_at: ethnicityFields.modified_at;
    deleted_at: ethnicityFields.deleted_at;

}

export namespace frontline_accountFields {
    export type frontline_account_id = number;
    export type frontline_api_key = string;
    export type frontline_workspace_id = string;
    export type nexmo_number = string | null;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface frontline_account {
    frontline_account_id: frontline_accountFields.frontline_account_id;
    frontline_api_key: frontline_accountFields.frontline_api_key;
    frontline_workspace_id: frontline_accountFields.frontline_workspace_id;
    nexmo_number: frontline_accountFields.nexmo_number;
    created_at: frontline_accountFields.created_at;
    modified_at: frontline_accountFields.modified_at;
    deleted_at: frontline_accountFields.deleted_at;

}

export namespace frontline_survey_answerFields {
    export type frontline_survey_answer_id = number;
    export type frontline_survey_question_id = number;
    export type organisation_id = number;
    export type answer_text = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface frontline_survey_answer {
    frontline_survey_answer_id: frontline_survey_answerFields.frontline_survey_answer_id;
    frontline_survey_question_id: frontline_survey_answerFields.frontline_survey_question_id;
    organisation_id: frontline_survey_answerFields.organisation_id;
    answer_text: frontline_survey_answerFields.answer_text;
    created_at: frontline_survey_answerFields.created_at;
    modified_at: frontline_survey_answerFields.modified_at;
    deleted_at: frontline_survey_answerFields.deleted_at;

}

export namespace frontline_survey_questionFields {
    export type frontline_survey_question_id = number;
    export type activity_key = string;
    export type frontline_question_uuid = string;
    export type frontline_survey_uuid = string;
    export type frontline_question_sequence = number;
    export type question_text = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface frontline_survey_question {
    frontline_survey_question_id: frontline_survey_questionFields.frontline_survey_question_id;
    activity_key: frontline_survey_questionFields.activity_key;
    frontline_question_uuid: frontline_survey_questionFields.frontline_question_uuid;
    frontline_survey_uuid: frontline_survey_questionFields.frontline_survey_uuid;
    frontline_question_sequence: frontline_survey_questionFields.frontline_question_sequence;
    question_text: frontline_survey_questionFields.question_text;
    created_at: frontline_survey_questionFields.created_at;
    modified_at: frontline_survey_questionFields.modified_at;
    deleted_at: frontline_survey_questionFields.deleted_at;

}

export namespace funding_bodyFields {
    export type organisation_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface funding_body {
    organisation_id: funding_bodyFields.organisation_id;
    created_at: funding_bodyFields.created_at;
    modified_at: funding_bodyFields.modified_at;
    deleted_at: funding_bodyFields.deleted_at;

}

export namespace funding_programmeFields {
    export type funding_programme_id = number;
    export type organisation_id = number;
    export type funding_programme_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface funding_programme {
    funding_programme_id: funding_programmeFields.funding_programme_id;
    organisation_id: funding_programmeFields.organisation_id;
    funding_programme_name: funding_programmeFields.funding_programme_name;
    created_at: funding_programmeFields.created_at;
    modified_at: funding_programmeFields.modified_at;
    deleted_at: funding_programmeFields.deleted_at;

}

export namespace funding_programme_community_businessFields {
    export type funding_programme_id = number;
    export type organisation_id = number;
    export type membership_status = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface funding_programme_community_business {
    funding_programme_id: funding_programme_community_businessFields.funding_programme_id;
    organisation_id: funding_programme_community_businessFields.organisation_id;
    membership_status: funding_programme_community_businessFields.membership_status;
    created_at: funding_programme_community_businessFields.created_at;
    modified_at: funding_programme_community_businessFields.modified_at;
    deleted_at: funding_programme_community_businessFields.deleted_at;

}

export namespace genderFields {
    export type gender_id = number;
    export type gender_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface gender {
    gender_id: genderFields.gender_id;
    gender_name: genderFields.gender_name;
    created_at: genderFields.created_at;
    modified_at: genderFields.modified_at;
    deleted_at: genderFields.deleted_at;

}

export namespace geography_columnsFields {
    export type f_table_catalog = string | null;
    export type f_table_schema = string | null;
    export type f_table_name = string | null;
    export type f_geography_column = string | null;
    export type coord_dimension = number | null;
    export type srid = number | null;
    export type type = string | null;

}

export interface geography_columns {
    f_table_catalog: geography_columnsFields.f_table_catalog;
    f_table_schema: geography_columnsFields.f_table_schema;
    f_table_name: geography_columnsFields.f_table_name;
    f_geography_column: geography_columnsFields.f_geography_column;
    coord_dimension: geography_columnsFields.coord_dimension;
    srid: geography_columnsFields.srid;
    type: geography_columnsFields.type;

}

export namespace geometry_columnsFields {
    export type f_table_catalog = string | null;
    export type f_table_schema = string | null;
    export type f_table_name = string | null;
    export type f_geometry_column = string | null;
    export type coord_dimension = number | null;
    export type srid = number | null;
    export type type = string | null;

}

export interface geometry_columns {
    f_table_catalog: geometry_columnsFields.f_table_catalog;
    f_table_schema: geometry_columnsFields.f_table_schema;
    f_table_name: geometry_columnsFields.f_table_name;
    f_geometry_column: geometry_columnsFields.f_geometry_column;
    coord_dimension: geometry_columnsFields.coord_dimension;
    srid: geometry_columnsFields.srid;
    type: geometry_columnsFields.type;

}

export namespace knex_migrationsFields {
    export type id = number;
    export type name = string | null;
    export type batch = number | null;
    export type migration_time = Date | null;

}

export interface knex_migrations {
    id: knex_migrationsFields.id;
    name: knex_migrationsFields.name;
    batch: knex_migrationsFields.batch;
    migration_time: knex_migrationsFields.migration_time;

}

export namespace knex_migrations_lockFields {
    export type index = number;
    export type is_locked = number | null;

}

export interface knex_migrations_lock {
    index: knex_migrations_lockFields.index;
    is_locked: knex_migrations_lockFields.is_locked;

}

export namespace login_eventFields {
    export type login_event_id = number;
    export type user_account_id = number;
    export type created_at = Date;
    export type deleted_at = Date | null;

}

export interface login_event {
    login_event_id: login_eventFields.login_event_id;
    user_account_id: login_eventFields.user_account_id;
    created_at: login_eventFields.created_at;
    deleted_at: login_eventFields.deleted_at;

}

export namespace nps_survey_benchmark_dataFields {
    export type nps_survey_benchmark_data_id = number;
    export type frontline_survey_question_id = number;
    export type detractors = number;
    export type passives = number;
    export type promoters = number;
    export type benchmark_year = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface nps_survey_benchmark_data {
    nps_survey_benchmark_data_id: nps_survey_benchmark_dataFields.nps_survey_benchmark_data_id;
    frontline_survey_question_id: nps_survey_benchmark_dataFields.frontline_survey_question_id;
    detractors: nps_survey_benchmark_dataFields.detractors;
    passives: nps_survey_benchmark_dataFields.passives;
    promoters: nps_survey_benchmark_dataFields.promoters;
    benchmark_year: nps_survey_benchmark_dataFields.benchmark_year;
    created_at: nps_survey_benchmark_dataFields.created_at;
    modified_at: nps_survey_benchmark_dataFields.modified_at;
    deleted_at: nps_survey_benchmark_dataFields.deleted_at;

}

export namespace organisationFields {
    export type organisation_id = number;
    export type organisation_name = string;
    export type _360_giving_id = string | null;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;
    export type is_temp = boolean | null;

}

export interface organisation {
    organisation_id: organisationFields.organisation_id;
    organisation_name: organisationFields.organisation_name;
    _360_giving_id: organisationFields._360_giving_id;
    created_at: organisationFields.created_at;
    modified_at: organisationFields.modified_at;
    deleted_at: organisationFields.deleted_at;
    is_temp: organisationFields.is_temp;

}

export namespace outreach_campaignFields {
    export type outreach_campaign_id = number;
    export type outreach_campaign_name = string;
    export type outreach_type_id = number;
    export type organisation_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface outreach_campaign {
    outreach_campaign_id: outreach_campaignFields.outreach_campaign_id;
    outreach_campaign_name: outreach_campaignFields.outreach_campaign_name;
    outreach_type_id: outreach_campaignFields.outreach_type_id;
    organisation_id: outreach_campaignFields.organisation_id;
    created_at: outreach_campaignFields.created_at;
    modified_at: outreach_campaignFields.modified_at;
    deleted_at: outreach_campaignFields.deleted_at;

}

export namespace outreach_campaign_targetFields {
    export type outreach_campaign_target_type_id = number;
    export type outreach_type_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface outreach_campaign_target {
    outreach_campaign_target_type_id: outreach_campaign_targetFields.outreach_campaign_target_type_id;
    outreach_type_id: outreach_campaign_targetFields.outreach_type_id;
    created_at: outreach_campaign_targetFields.created_at;
    modified_at: outreach_campaign_targetFields.modified_at;
    deleted_at: outreach_campaign_targetFields.deleted_at;

}

export namespace outreach_campaign_target_typeFields {
    export type outreach_campaign_target_type_id = number;
    export type outreach_campaign_target_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface outreach_campaign_target_type {
    outreach_campaign_target_type_id: outreach_campaign_target_typeFields.outreach_campaign_target_type_id;
    outreach_campaign_target_name: outreach_campaign_target_typeFields.outreach_campaign_target_name;
    created_at: outreach_campaign_target_typeFields.created_at;
    modified_at: outreach_campaign_target_typeFields.modified_at;
    deleted_at: outreach_campaign_target_typeFields.deleted_at;

}

export namespace outreach_meetingFields {
    export type outreach_meeting_id = number;
    export type user_account_id = number;
    export type outreach_campaign_id = number;
    export type outreach_meeting_type_id = number;
    export type outreach_partner = string;
    export type meeting_subject = string;
    export type scheduled_at = Date | null;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface outreach_meeting {
    outreach_meeting_id: outreach_meetingFields.outreach_meeting_id;
    user_account_id: outreach_meetingFields.user_account_id;
    outreach_campaign_id: outreach_meetingFields.outreach_campaign_id;
    outreach_meeting_type_id: outreach_meetingFields.outreach_meeting_type_id;
    outreach_partner: outreach_meetingFields.outreach_partner;
    meeting_subject: outreach_meetingFields.meeting_subject;
    scheduled_at: outreach_meetingFields.scheduled_at;
    created_at: outreach_meetingFields.created_at;
    modified_at: outreach_meetingFields.modified_at;
    deleted_at: outreach_meetingFields.deleted_at;

}

export namespace outreach_meeting_typeFields {
    export type outreach_meeting_type_id = number;
    export type outreach_meeting_type_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface outreach_meeting_type {
    outreach_meeting_type_id: outreach_meeting_typeFields.outreach_meeting_type_id;
    outreach_meeting_type_name: outreach_meeting_typeFields.outreach_meeting_type_name;
    created_at: outreach_meeting_typeFields.created_at;
    modified_at: outreach_meeting_typeFields.modified_at;
    deleted_at: outreach_meeting_typeFields.deleted_at;

}

export namespace outreach_typeFields {
    export type outreach_type_id = number;
    export type outreach_type_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface outreach_type {
    outreach_type_id: outreach_typeFields.outreach_type_id;
    outreach_type_name: outreach_typeFields.outreach_type_name;
    created_at: outreach_typeFields.created_at;
    modified_at: outreach_typeFields.modified_at;
    deleted_at: outreach_typeFields.deleted_at;

}

export namespace permissionFields {
    export type permission_id = number;
    export type permission_entity = string;
    export type permission_level = enum_permission_level;
    export type access_type = enum_access_type;

}

export interface permission {
    permission_id: permissionFields.permission_id;
    permission_entity: permissionFields.permission_entity;
    permission_level: permissionFields.permission_level;
    access_type: permissionFields.access_type;

}

export namespace raster_columnsFields {
    export type r_table_catalog = string | null;
    export type r_table_schema = string | null;
    export type r_table_name = string | null;
    export type r_raster_column = string | null;
    export type srid = number | null;
    export type scale_x = number | null;
    export type scale_y = number | null;
    export type blocksize_x = number | null;
    export type blocksize_y = number | null;
    export type same_alignment = boolean | null;
    export type regular_blocking = boolean | null;
    export type num_bands = number | null;
    export type pixel_types = Array<string> | null;
    export type nodata_values = Array<number> | null;
    export type out_db = Array<boolean> | null;
    export type extent = any | null;
    export type spatial_index = boolean | null;

}

export interface raster_columns {
    r_table_catalog: raster_columnsFields.r_table_catalog;
    r_table_schema: raster_columnsFields.r_table_schema;
    r_table_name: raster_columnsFields.r_table_name;
    r_raster_column: raster_columnsFields.r_raster_column;
    srid: raster_columnsFields.srid;
    scale_x: raster_columnsFields.scale_x;
    scale_y: raster_columnsFields.scale_y;
    blocksize_x: raster_columnsFields.blocksize_x;
    blocksize_y: raster_columnsFields.blocksize_y;
    same_alignment: raster_columnsFields.same_alignment;
    regular_blocking: raster_columnsFields.regular_blocking;
    num_bands: raster_columnsFields.num_bands;
    pixel_types: raster_columnsFields.pixel_types;
    nodata_values: raster_columnsFields.nodata_values;
    out_db: raster_columnsFields.out_db;
    extent: raster_columnsFields.extent;
    spatial_index: raster_columnsFields.spatial_index;

}

export namespace raster_overviewsFields {
    export type o_table_catalog = string | null;
    export type o_table_schema = string | null;
    export type o_table_name = string | null;
    export type o_raster_column = string | null;
    export type r_table_catalog = string | null;
    export type r_table_schema = string | null;
    export type r_table_name = string | null;
    export type r_raster_column = string | null;
    export type overview_factor = number | null;

}

export interface raster_overviews {
    o_table_catalog: raster_overviewsFields.o_table_catalog;
    o_table_schema: raster_overviewsFields.o_table_schema;
    o_table_name: raster_overviewsFields.o_table_name;
    o_raster_column: raster_overviewsFields.o_raster_column;
    r_table_catalog: raster_overviewsFields.r_table_catalog;
    r_table_schema: raster_overviewsFields.r_table_schema;
    r_table_name: raster_overviewsFields.r_table_name;
    r_raster_column: raster_overviewsFields.r_raster_column;
    overview_factor: raster_overviewsFields.overview_factor;

}

export namespace single_use_tokenFields {
    export type single_use_token_id = number;
    export type token = string;
    export type created_at = Date;
    export type expires_at = Date;
    export type used_at = Date | null;
    export type deleted_at = Date | null;

}

export interface single_use_token {
    single_use_token_id: single_use_tokenFields.single_use_token_id;
    token: single_use_tokenFields.token;
    created_at: single_use_tokenFields.created_at;
    expires_at: single_use_tokenFields.expires_at;
    used_at: single_use_tokenFields.used_at;
    deleted_at: single_use_tokenFields.deleted_at;

}

export namespace spatial_ref_sysFields {
    export type srid = number;
    export type auth_name = string | null;
    export type auth_srid = number | null;
    export type srtext = string | null;
    export type proj4text = string | null;

}

export interface spatial_ref_sys {
    srid: spatial_ref_sysFields.srid;
    auth_name: spatial_ref_sysFields.auth_name;
    auth_srid: spatial_ref_sysFields.auth_srid;
    srtext: spatial_ref_sysFields.srtext;
    proj4text: spatial_ref_sysFields.proj4text;

}

export namespace subscriptionFields {
    export type subscription_id = number;
    export type owner_id = number;
    export type beneficiary_id = number | null;
    export type frontline_account_id = number;
    export type subscription_type_id = number;
    export type subscription_status = enum_subscription_status;
    export type expires_at = Date;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface subscription {
    subscription_id: subscriptionFields.subscription_id;
    owner_id: subscriptionFields.owner_id;
    beneficiary_id: subscriptionFields.beneficiary_id;
    frontline_account_id: subscriptionFields.frontline_account_id;
    subscription_type_id: subscriptionFields.subscription_type_id;
    subscription_status: subscriptionFields.subscription_status;
    expires_at: subscriptionFields.expires_at;
    created_at: subscriptionFields.created_at;
    modified_at: subscriptionFields.modified_at;
    deleted_at: subscriptionFields.deleted_at;

}

export namespace subscription_typeFields {
    export type subscription_type_id = number;
    export type subscription_type_name = string;

}

export interface subscription_type {
    subscription_type_id: subscription_typeFields.subscription_type_id;
    subscription_type_name: subscription_typeFields.subscription_type_name;

}

export namespace training_sessionFields {
    export type training_session_id = number;
    export type notes = string | null;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface training_session {
    training_session_id: training_sessionFields.training_session_id;
    notes: training_sessionFields.notes;
    created_at: training_sessionFields.created_at;
    modified_at: training_sessionFields.modified_at;
    deleted_at: training_sessionFields.deleted_at;

}

export namespace training_session_organisationFields {
    export type training_session_id = number;
    export type organisation_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface training_session_organisation {
    training_session_id: training_session_organisationFields.training_session_id;
    organisation_id: training_session_organisationFields.organisation_id;
    created_at: training_session_organisationFields.created_at;
    modified_at: training_session_organisationFields.modified_at;
    deleted_at: training_session_organisationFields.deleted_at;

}

export namespace user_accountFields {
    export type user_account_id = number;
    export type user_name = string;
    export type user_password = string | null;
    export type qr_code = string | null;
    export type gender_id = number;
    export type disability_id = number;
    export type ethnicity_id = number;
    export type email = string | null;
    export type phone_number = string | null;
    export type post_code = string | null;
    export type birth_year = number | null;
    export type is_email_confirmed = boolean;
    export type is_phone_number_confirmed = boolean;
    export type is_email_contact_consent_granted = boolean;
    export type is_sms_contact_consent_granted = boolean;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;
    export type is_temp = boolean | null;

}

export interface user_account {
    user_account_id: user_accountFields.user_account_id;
    user_name: user_accountFields.user_name;
    user_password: user_accountFields.user_password;
    qr_code: user_accountFields.qr_code;
    gender_id: user_accountFields.gender_id;
    disability_id: user_accountFields.disability_id;
    ethnicity_id: user_accountFields.ethnicity_id;
    email: user_accountFields.email;
    phone_number: user_accountFields.phone_number;
    post_code: user_accountFields.post_code;
    birth_year: user_accountFields.birth_year;
    is_email_confirmed: user_accountFields.is_email_confirmed;
    is_phone_number_confirmed: user_accountFields.is_phone_number_confirmed;
    is_email_contact_consent_granted: user_accountFields.is_email_contact_consent_granted;
    is_sms_contact_consent_granted: user_accountFields.is_sms_contact_consent_granted;
    created_at: user_accountFields.created_at;
    modified_at: user_accountFields.modified_at;
    deleted_at: user_accountFields.deleted_at;
    is_temp: user_accountFields.is_temp;

}

export namespace user_account_access_roleFields {
    export type user_account_access_role_id = number;
    export type user_account_id = number;
    export type access_role_id = number;
    export type organisation_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface user_account_access_role {
    user_account_access_role_id: user_account_access_roleFields.user_account_access_role_id;
    user_account_id: user_account_access_roleFields.user_account_id;
    access_role_id: user_account_access_roleFields.access_role_id;
    organisation_id: user_account_access_roleFields.organisation_id;
    created_at: user_account_access_roleFields.created_at;
    modified_at: user_account_access_roleFields.modified_at;
    deleted_at: user_account_access_roleFields.deleted_at;

}

export namespace user_account_active_dayFields {
    export type user_account_active_day_id = number;
    export type user_account_id = number;
    export type origin = string;
    export type created_at = Date;
    export type deleted_at = Date | null;

}

export interface user_account_active_day {
    user_account_active_day_id: user_account_active_dayFields.user_account_active_day_id;
    user_account_id: user_account_active_dayFields.user_account_id;
    origin: user_account_active_dayFields.origin;
    created_at: user_account_active_dayFields.created_at;
    deleted_at: user_account_active_dayFields.deleted_at;

}

export namespace user_secret_resetFields {
    export type user_secret_reset_id = number;
    export type user_account_id = number;
    export type single_use_token_id = number;

}

export interface user_secret_reset {
    user_secret_reset_id: user_secret_resetFields.user_secret_reset_id;
    user_account_id: user_secret_resetFields.user_account_id;
    single_use_token_id: user_secret_resetFields.single_use_token_id;

}

export namespace visit_activityFields {
    export type visit_activity_id = number;
    export type organisation_id = number;
    export type visit_activity_category_id = number | null;
    export type visit_activity_name = string;
    export type monday = boolean;
    export type tuesday = boolean;
    export type wednesday = boolean;
    export type thursday = boolean;
    export type friday = boolean;
    export type saturday = boolean;
    export type sunday = boolean;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface visit_activity {
    visit_activity_id: visit_activityFields.visit_activity_id;
    organisation_id: visit_activityFields.organisation_id;
    visit_activity_category_id: visit_activityFields.visit_activity_category_id;
    visit_activity_name: visit_activityFields.visit_activity_name;
    monday: visit_activityFields.monday;
    tuesday: visit_activityFields.tuesday;
    wednesday: visit_activityFields.wednesday;
    thursday: visit_activityFields.thursday;
    friday: visit_activityFields.friday;
    saturday: visit_activityFields.saturday;
    sunday: visit_activityFields.sunday;
    created_at: visit_activityFields.created_at;
    modified_at: visit_activityFields.modified_at;
    deleted_at: visit_activityFields.deleted_at;

}

export namespace visit_activity_categoryFields {
    export type visit_activity_category_id = number;
    export type visit_activity_category_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface visit_activity_category {
    visit_activity_category_id: visit_activity_categoryFields.visit_activity_category_id;
    visit_activity_category_name: visit_activity_categoryFields.visit_activity_category_name;
    created_at: visit_activity_categoryFields.created_at;
    modified_at: visit_activity_categoryFields.modified_at;
    deleted_at: visit_activity_categoryFields.deleted_at;

}

export namespace visit_feedbackFields {
    export type visit_feedback_id = number;
    export type organisation_id = number;
    export type score = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface visit_feedback {
    visit_feedback_id: visit_feedbackFields.visit_feedback_id;
    organisation_id: visit_feedbackFields.organisation_id;
    score: visit_feedbackFields.score;
    created_at: visit_feedbackFields.created_at;
    modified_at: visit_feedbackFields.modified_at;
    deleted_at: visit_feedbackFields.deleted_at;

}

export namespace visit_logFields {
    export type visit_log_id = number;
    export type user_account_id = number;
    export type visit_activity_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface visit_log {
    visit_log_id: visit_logFields.visit_log_id;
    user_account_id: visit_logFields.user_account_id;
    visit_activity_id: visit_logFields.visit_activity_id;
    created_at: visit_logFields.created_at;
    modified_at: visit_logFields.modified_at;
    deleted_at: visit_logFields.deleted_at;

}

export namespace volunteer_activityFields {
    export type volunteer_activity_id = number;
    export type volunteer_activity_name = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface volunteer_activity {
    volunteer_activity_id: volunteer_activityFields.volunteer_activity_id;
    volunteer_activity_name: volunteer_activityFields.volunteer_activity_name;
    created_at: volunteer_activityFields.created_at;
    modified_at: volunteer_activityFields.modified_at;
    deleted_at: volunteer_activityFields.deleted_at;

}

export namespace volunteer_admin_codeFields {
    export type volunteer_admin_code_id = number;
    export type organisation_id = number;
    export type code = string;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface volunteer_admin_code {
    volunteer_admin_code_id: volunteer_admin_codeFields.volunteer_admin_code_id;
    organisation_id: volunteer_admin_codeFields.organisation_id;
    code: volunteer_admin_codeFields.code;
    created_at: volunteer_admin_codeFields.created_at;
    modified_at: volunteer_admin_codeFields.modified_at;
    deleted_at: volunteer_admin_codeFields.deleted_at;

}

export namespace volunteer_hours_logFields {
    export type volunteer_hours_log_id = number;
    export type volunteer_activity_id = number;
    export type volunteer_project_id = number | null;
    export type user_account_id = number;
    export type organisation_id = number;
    export type duration = string;
    export type started_at = Date;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;
    export type created_by = number | null;

}

export interface volunteer_hours_log {
    volunteer_hours_log_id: volunteer_hours_logFields.volunteer_hours_log_id;
    volunteer_activity_id: volunteer_hours_logFields.volunteer_activity_id;
    volunteer_project_id: volunteer_hours_logFields.volunteer_project_id;
    user_account_id: volunteer_hours_logFields.user_account_id;
    organisation_id: volunteer_hours_logFields.organisation_id;
    duration: volunteer_hours_logFields.duration;
    started_at: volunteer_hours_logFields.started_at;
    created_at: volunteer_hours_logFields.created_at;
    modified_at: volunteer_hours_logFields.modified_at;
    deleted_at: volunteer_hours_logFields.deleted_at;
    created_by: volunteer_hours_logFields.created_by;

}

export namespace volunteer_projectFields {
    export type volunteer_project_id = number;
    export type volunteer_project_name = string;
    export type organisation_id = number;
    export type created_at = Date;
    export type modified_at = Date | null;
    export type deleted_at = Date | null;

}

export interface volunteer_project {
    volunteer_project_id: volunteer_projectFields.volunteer_project_id;
    volunteer_project_name: volunteer_projectFields.volunteer_project_name;
    organisation_id: volunteer_projectFields.organisation_id;
    created_at: volunteer_projectFields.created_at;
    modified_at: volunteer_projectFields.modified_at;
    deleted_at: volunteer_projectFields.deleted_at;

}
