exports.seed = (knex) =>
  knex('frontline_survey_question')
    .insert([
      {
        activity_key: '2q_survey.1.research_agreement.ckbk',
        frontline_question_uuid: "a",
        frontline_survey_uuid: 1,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '2q_survey.1.research_agreement.ckbk',
        frontline_question_uuid: "b",
        frontline_survey_uuid: 1,
        frontline_question_sequence: 2,
        question_text: '',
        deleted_at: new Date(),
      },
      {
        activity_key: '02.2q_survey.impact_research_agreement.ckbk',
        frontline_question_uuid: "c",
        frontline_survey_uuid: 2,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '02.2q_survey.impact_research_agreement.ckbk',
        frontline_question_uuid: "d",
        frontline_survey_uuid: 2,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '2q_survey.3.nps.ckbk',
        frontline_question_uuid: "e",
        frontline_survey_uuid: 3,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '2q_survey.3.nps.ckbk',
        frontline_question_uuid: "f",
        frontline_survey_uuid: 3,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '2q_survey.4.trust.ckbk',
        frontline_question_uuid: 'g',
        frontline_survey_uuid: 4,
        frontline_question_sequence: 1,
        question_text: ''
      },
      {
        activity_key: '2q_survey.4.trust.ckbk',
        frontline_question_uuid: 'h',
        frontline_survey_uuid: 4,
        frontline_question_sequence: 2,
        question_text: ''
      },
      {
        activity_key: '05.3q_survey.neighbourhood_satisfaction.ckbk',
        frontline_question_uuid: "i",
        frontline_survey_uuid: 5,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '05.3q_survey.neighbourhood_satisfaction.ckbk',
        frontline_question_uuid: "j",
        frontline_survey_uuid: 5,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '05.3q_survey.neighbourhood_satisfaction.ckbk',
        frontline_question_uuid: "j2",
        frontline_survey_uuid: 5,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '1q_survey.6.physical_health.ckbk',
        frontline_question_uuid: "k",
        frontline_survey_uuid: 6,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '1q_survey.7.open_feedback.ckbk',
        frontline_question_uuid: "l",
        frontline_survey_uuid: 7,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '1q_survey.11.wellbeing_changes_pt2.ckbk',
        frontline_question_uuid: "m",
        frontline_survey_uuid: 11,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '12.3q_survey.staff_satisfaction.ckbk',
        frontline_question_uuid: "n",
        frontline_survey_uuid: 12,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '12.3q_survey.staff_satisfaction.ckbk',
        frontline_question_uuid: "o",
        frontline_survey_uuid: 12,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '12.3q_survey.staff_satisfaction.ckbk',
        frontline_question_uuid: "o2",
        frontline_survey_uuid: 12,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '13.3q_survey.volunteer_satisfaction.ckbk',
        frontline_question_uuid: "p",
        frontline_survey_uuid: 13,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '13.3q_survey.volunteer_satisfaction.ckbk',
        frontline_question_uuid: "q",
        frontline_survey_uuid: 13,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '13.3q_survey.volunteer_satisfaction.ckbk',
        frontline_question_uuid: "q2",
        frontline_survey_uuid: 13,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '2q_survey.14.agm_voting.ckbk',
        frontline_question_uuid: "r",
        frontline_survey_uuid: 14,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '2q_survey.14.agm_voting.ckbk',
        frontline_question_uuid: "s",
        frontline_survey_uuid: 14,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '3q_survey.15.wellbeing_changes_pt1.ckbk',
        frontline_question_uuid: "t",
        frontline_survey_uuid: 15,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '3q_survey.15.wellbeing_changes_pt1.ckbk',
        frontline_question_uuid: "u",
        frontline_survey_uuid: 15,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '3q_survey.15.wellbeing_changes_pt1.ckbk',
        frontline_question_uuid: "v",
        frontline_survey_uuid: 15,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '16.4q_survey.job_satisfaction.ckbk',
        frontline_question_uuid: "w",
        frontline_survey_uuid: 16,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '16.4q_survey.job_satisfaction.ckbk',
        frontline_question_uuid: "x",
        frontline_survey_uuid: 16,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '16.4q_survey.job_satisfaction.ckbk',
        frontline_question_uuid: "y",
        frontline_survey_uuid: 16,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '16.4q_survey.job_satisfaction.ckbk',
        frontline_question_uuid: "y2",
        frontline_survey_uuid: 16,
        frontline_question_sequence: 4,
        question_text: '',
      },
      {
        activity_key: '3q_survey.17.events.ckbk',
        frontline_question_uuid: "z",
        frontline_survey_uuid: 17,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '3q_survey.17.events.ckbk',
        frontline_question_uuid: "aa",
        frontline_survey_uuid: 17,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '3q_survey.17.events.ckbk',
        frontline_question_uuid: "ab",
        frontline_survey_uuid: 17,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '3q_survey.18.wellbeing_changes.ckbk',
        frontline_question_uuid: "ac",
        frontline_survey_uuid: 18,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '3q_survey.18.wellbeing_changes.ckbk',
        frontline_question_uuid: "ad",
        frontline_survey_uuid: 18,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '3q_survey.18.wellbeing_changes.ckbk',
        frontline_question_uuid: "ae",
        frontline_survey_uuid: 18,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '2q_survey.19.intercultural_cohesion.ckbk',
        frontline_question_uuid: "af",
        frontline_survey_uuid: 19,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '2q_survey.19.intercultural_cohesion.ckbk',
        frontline_question_uuid: "ag",
        frontline_survey_uuid: 19,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '20.3q_survey.confidence.ckbk',
        frontline_question_uuid: "ah",
        frontline_survey_uuid: 20,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '20.3q_survey.confidence.ckbk',
        frontline_question_uuid: "ai",
        frontline_survey_uuid: 20,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '20.3q_survey.confidence.ckbk',
        frontline_question_uuid: "aj",
        frontline_survey_uuid: 20,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '21.3q_survey.business_support_feedback.ckbk',
        frontline_question_uuid: "ak",
        frontline_survey_uuid: 21,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '21.3q_survey.business_support_feedback.ckbk',
        frontline_question_uuid: "al",
        frontline_survey_uuid: 21,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '21.3q_survey.business_support_feedback.ckbk',
        frontline_question_uuid: "am",
        frontline_survey_uuid: 21,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '22.3q_survey.community_consultation.ckbk',
        frontline_question_uuid: "an",
        frontline_survey_uuid: 22,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '22.3q_survey.community_consultation.ckbk',
        frontline_question_uuid: "ao",
        frontline_survey_uuid: 22,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '22.3q_survey.community_consultation.ckbk',
        frontline_question_uuid: "ap",
        frontline_survey_uuid: 22,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '18.3q_survey.wellbeing_changes.ckbk',
        frontline_question_uuid: "aq",
        frontline_survey_uuid: 18,
        frontline_question_sequence: 4,
        question_text: '',
      },
      {
        activity_key: '20.3q_survey.confidence.ckbk',
        frontline_question_uuid: "ar",
        frontline_survey_uuid: 20,
        frontline_question_sequence: 4,
        question_text: '',
      },
      {
        activity_key: '24.3q_survey.workshop_evaluation.ckbk',
        frontline_question_uuid: "as",
        frontline_survey_uuid: 24,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '24.3q_survey.workshop_evaluation.ckbk',
        frontline_question_uuid: "at",
        frontline_survey_uuid: 24,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '24.3q_survey.workshop_evaluation.ckbk',
        frontline_question_uuid: "au",
        frontline_survey_uuid: 24,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '25.3q_survey.community_engagement.ckbk',
        frontline_question_uuid: "av",
        frontline_survey_uuid: 25,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '25.3q_survey.community_engagement.ckbk',
        frontline_question_uuid: "aw",
        frontline_survey_uuid: 25,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '25.3q_survey.community_engagement.ckbk',
        frontline_question_uuid: "ax",
        frontline_survey_uuid: 25,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '26.1q_survey.share_offer_check-in.ckbk',
        frontline_question_uuid: "ay",
        frontline_survey_uuid: 26,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '27.3q_survey.beneficiary_goal_check-in.ckbk',
        frontline_question_uuid: "az",
        frontline_survey_uuid: 27,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '27.3q_survey.beneficiary_goal_check-in.ckbk',
        frontline_question_uuid: "ba",
        frontline_survey_uuid: 27,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '27.3q_survey.beneficiary_goal_check-in.ckbk',
        frontline_question_uuid: "bb",
        frontline_survey_uuid: 27,
        frontline_question_sequence: 3,
        question_text: '',
      },
      {
        activity_key: '28.3q_survey.employability.ckbk',
        frontline_question_uuid: "bc",
        frontline_survey_uuid: 28,
        frontline_question_sequence: 1,
        question_text: '',
      },
      {
        activity_key: '28.3q_survey.employability.ckbk',
        frontline_question_uuid: "bd",
        frontline_survey_uuid: 28,
        frontline_question_sequence: 2,
        question_text: '',
      },
      {
        activity_key: '28.3q_survey.employability.ckbk',
        frontline_question_uuid: "be",
        frontline_survey_uuid: 28,
        frontline_question_sequence: 3,
        question_text: '',
      },
    ]);
