export enum ColoursEnum {
  black = '#333333',
  white = '#FFFFFF',
  transparentWhite = 'rgb(255, 255, 255, 0.9)',
  lightGrey = '#F8F8F8',
  grey = '#B7B7B7',
  darkGrey = '#707070',
  orange = '#FFBF00',
  purple = '#8000FF',
  red = '#F44336',
}

export enum GraphColoursEnum {
  red = '#E36860',
  pink = '#EF7CA3',
  violet = '#9C78D9',
  purple = '#6370BC',
  blue = '#47ABFA',
  emerald = '#379A90',
  green = '#6DB26F',
  lime = '#D7E360',
  sunrise = '#FDAF3A',
  orange = '#FC855F',
  brown = '#8B7972',
  grey = '#9CAEB5',
  darkRed= '#D32F2F',
  darkPink= '#C2185B',
  darkVoilet = '#512DA8',
  darkPurple = '#651FFF',
  darkBlue = '#1565C0',
  darkEmerald = '#00695C',
  darkGreen = '#2E7D32',
  darkLime = '#AFB42B',
  darkSunrise = '#E65100',
  darkOrange = '#BF360C',
  darkBrown = '#5D4037',
  darkGrey = '#757575',
}

export const GraphColourList = [
  GraphColoursEnum.red,
  GraphColoursEnum.pink,
  GraphColoursEnum.violet,
  GraphColoursEnum.purple,
  GraphColoursEnum.blue,
  GraphColoursEnum.green,
  GraphColoursEnum.lime,
  GraphColoursEnum.sunrise,
  GraphColoursEnum.orange,
  GraphColoursEnum.brown,
  GraphColoursEnum.grey,
  GraphColoursEnum.darkRed,
  GraphColoursEnum.darkPink,
  GraphColoursEnum.darkVoilet,
  GraphColoursEnum.darkPurple,
  GraphColoursEnum.darkBlue,
  GraphColoursEnum.darkEmerald,
  GraphColoursEnum.darkGreen,
  GraphColoursEnum.darkLime,
  GraphColoursEnum.darkSunrise,
  GraphColoursEnum.darkOrange,
  GraphColoursEnum.darkBrown,
  GraphColoursEnum.darkGrey,
];
